services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onn-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/onamnotifier
      SPRING_DATASOURCE_USERNAME: ${ADMIN_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ADMIN_PASSWORD}

      ADMIN_EMAILS: ${ADMIN_EMAILS}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_TOKEN_SECRET: ${JWT_TOKEN_SECRET}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: onamnotifier
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ADMIN_USERNAME} -d onamnotifier"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: